// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type LanguagesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/languages_controller.ts').default['show'], false>
}
type RegisterPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['register'], false>
}
type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], true>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type MeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['me'], false>
}
type PasswordPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['changePasswordValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['changePassword'], true>
}
type UsersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['index'], false>
}
type UsersPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['store'], false>
}
type UsersIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['show'], false>
}
type UsersIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/user.ts')['putUserValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['update'], true>
}
type UsersIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/users_controller.ts').default['destroy'], false>
}
type HousingsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['index'], false>
}
type HousingsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/housing.ts')['postHousingValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['store'], true>
}
type HousingsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['show'], false>
}
type HousingsIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/housing.ts')['putHousingValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['update'], true>
}
type HousingsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['destroy'], false>
}
type ImagesPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/image.ts')['imageValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/images_controller.ts').default['store'], true>
}
type ImagesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/images_controller.ts').default['show'], false>
}
type ImagesIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/images_controller.ts').default['destroy'], false>
}
type JobsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['index'], false>
}
type JobsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['store'], false>
}
type JobsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['show'], false>
}
type JobsIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/job.ts')['putJobValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['update'], true>
}
type JobsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['destroy'], false>
}
type HousingConditionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['housingConditions'], false>
}
type HousingOfferTypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['housingOfferTypes'], false>
}
type HousingTypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['housingTypes'], false>
}
type JobIndustriesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['jobIndustries'], false>
}
type JobTypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['jobTypes'], false>
}
type NewsletterSubscribersGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/newsletter_controller.ts').default['index'], false>
}
type NewsletterSubscribePost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/newsletter.ts')['newsletterValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/newsletter_controller.ts').default['subscribe'], true>
}
type NewsletterUnsubscribeIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/newsletter_controller.ts').default['unsubscribe'], false>
}
type NewsletterSendPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/newsletter.ts')['sendNewsletterValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/newsletter_controller.ts').default['send'], true>
}
type StatisticsGetHead = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/statistics.ts')['getStatisticsValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/statistics_controller.ts').default['show'], true>
}
export interface ApiDefinition {
  'languages': {
    '$url': {
    };
    '$get': LanguagesGetHead;
    '$head': LanguagesGetHead;
  };
  'register': {
    '$url': {
    };
    '$post': RegisterPost;
  };
  'login': {
    '$url': {
    };
    '$post': LoginPost;
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
  'me': {
    '$url': {
    };
    '$get': MeGetHead;
    '$head': MeGetHead;
  };
  'password': {
    '$url': {
    };
    '$patch': PasswordPatch;
  };
  'users': {
    '$url': {
    };
    '$get': UsersGetHead;
    '$head': UsersGetHead;
    '$post': UsersPost;
    ':id': {
      '$url': {
      };
      '$get': UsersIdGetHead;
      '$head': UsersIdGetHead;
      '$put': UsersIdPutPatch;
      '$patch': UsersIdPutPatch;
      '$delete': UsersIdDelete;
    };
  };
  'housings': {
    '$url': {
    };
    '$get': HousingsGetHead;
    '$head': HousingsGetHead;
    '$post': HousingsPost;
    ':id': {
      '$url': {
      };
      '$get': HousingsIdGetHead;
      '$head': HousingsIdGetHead;
      '$put': HousingsIdPutPatch;
      '$patch': HousingsIdPutPatch;
      '$delete': HousingsIdDelete;
    };
  };
  'images': {
    '$url': {
    };
    '$post': ImagesPost;
    ':name': {
      '$url': {
      };
      '$get': ImagesIdGetHead;
      '$head': ImagesIdGetHead;
      '$delete': ImagesIdDelete;
    };
  };
  'jobs': {
    '$url': {
    };
    '$get': JobsGetHead;
    '$head': JobsGetHead;
    '$post': JobsPost;
    ':id': {
      '$url': {
      };
      '$get': JobsIdGetHead;
      '$head': JobsIdGetHead;
      '$put': JobsIdPutPatch;
      '$patch': JobsIdPutPatch;
      '$delete': JobsIdDelete;
    };
  };
  'housing-conditions': {
    '$url': {
    };
    '$get': HousingConditionsGetHead;
    '$head': HousingConditionsGetHead;
  };
  'housing-offer-types': {
    '$url': {
    };
    '$get': HousingOfferTypesGetHead;
    '$head': HousingOfferTypesGetHead;
  };
  'housing-types': {
    '$url': {
    };
    '$get': HousingTypesGetHead;
    '$head': HousingTypesGetHead;
  };
  'job-industries': {
    '$url': {
    };
    '$get': JobIndustriesGetHead;
    '$head': JobIndustriesGetHead;
  };
  'job-types': {
    '$url': {
    };
    '$get': JobTypesGetHead;
    '$head': JobTypesGetHead;
  };
  'newsletter': {
    'subscribers': {
      '$url': {
      };
      '$get': NewsletterSubscribersGetHead;
      '$head': NewsletterSubscribersGetHead;
    };
    'subscribe': {
      '$url': {
      };
      '$post': NewsletterSubscribePost;
    };
    'unsubscribe': {
      ':id': {
        '$url': {
        };
        '$get': NewsletterUnsubscribeIdGetHead;
        '$head': NewsletterUnsubscribeIdGetHead;
      };
    };
    'send': {
      '$url': {
      };
      '$post': NewsletterSendPost;
    };
  };
  'statistics': {
    '$url': {
    };
    '$get': StatisticsGetHead;
    '$head': StatisticsGetHead;
  };
}
const routes = [
  {
    params: [],
    name: 'languages',
    path: '/languages',
    method: ["GET","HEAD"],
    types: {} as LanguagesGetHead,
  },
  {
    params: [],
    name: 'auth.register',
    path: '/register',
    method: ["POST"],
    types: {} as RegisterPost,
  },
  {
    params: [],
    name: 'auth.login',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/logout',
    method: ["POST"],
    types: {} as LogoutPost,
  },
  {
    params: [],
    name: 'auth.me',
    path: '/me',
    method: ["GET","HEAD"],
    types: {} as MeGetHead,
  },
  {
    params: [],
    name: 'auth.password',
    path: '/password',
    method: ["PATCH"],
    types: {} as PasswordPatch,
  },
  {
    params: [],
    name: 'users.index',
    path: '/users',
    method: ["GET","HEAD"],
    types: {} as UsersGetHead,
  },
  {
    params: [],
    name: 'users.store',
    path: '/users',
    method: ["POST"],
    types: {} as UsersPost,
  },
  {
    params: ["id"],
    name: 'users.show',
    path: '/users/:id',
    method: ["GET","HEAD"],
    types: {} as UsersIdGetHead,
  },
  {
    params: ["id"],
    name: 'users.update',
    path: '/users/:id',
    method: ["PUT","PATCH"],
    types: {} as UsersIdPutPatch,
  },
  {
    params: ["id"],
    name: 'users.destroy',
    path: '/users/:id',
    method: ["DELETE"],
    types: {} as UsersIdDelete,
  },
  {
    params: [],
    name: 'housings.index',
    path: '/housings',
    method: ["GET","HEAD"],
    types: {} as HousingsGetHead,
  },
  {
    params: [],
    name: 'housings.store',
    path: '/housings',
    method: ["POST"],
    types: {} as HousingsPost,
  },
  {
    params: ["id"],
    name: 'housings.show',
    path: '/housings/:id',
    method: ["GET","HEAD"],
    types: {} as HousingsIdGetHead,
  },
  {
    params: ["id"],
    name: 'housings.update',
    path: '/housings/:id',
    method: ["PUT","PATCH"],
    types: {} as HousingsIdPutPatch,
  },
  {
    params: ["id"],
    name: 'housings.destroy',
    path: '/housings/:id',
    method: ["DELETE"],
    types: {} as HousingsIdDelete,
  },
  {
    params: [],
    name: 'images.store',
    path: '/images',
    method: ["POST"],
    types: {} as ImagesPost,
  },
  {
    params: ["name"],
    name: 'images.show',
    path: '/images/:name',
    method: ["GET","HEAD"],
    types: {} as ImagesIdGetHead,
  },
  {
    params: ["name"],
    name: 'images.destroy',
    path: '/images/:name',
    method: ["DELETE"],
    types: {} as ImagesIdDelete,
  },
  {
    params: [],
    name: 'jobs.index',
    path: '/jobs',
    method: ["GET","HEAD"],
    types: {} as JobsGetHead,
  },
  {
    params: [],
    name: 'jobs.store',
    path: '/jobs',
    method: ["POST"],
    types: {} as JobsPost,
  },
  {
    params: ["id"],
    name: 'jobs.show',
    path: '/jobs/:id',
    method: ["GET","HEAD"],
    types: {} as JobsIdGetHead,
  },
  {
    params: ["id"],
    name: 'jobs.update',
    path: '/jobs/:id',
    method: ["PUT","PATCH"],
    types: {} as JobsIdPutPatch,
  },
  {
    params: ["id"],
    name: 'jobs.destroy',
    path: '/jobs/:id',
    method: ["DELETE"],
    types: {} as JobsIdDelete,
  },
  {
    params: [],
    name: 'offer-properties.housing-conditions',
    path: '/housing-conditions',
    method: ["GET","HEAD"],
    types: {} as HousingConditionsGetHead,
  },
  {
    params: [],
    name: 'offer-properties.housing-offer-types',
    path: '/housing-offer-types',
    method: ["GET","HEAD"],
    types: {} as HousingOfferTypesGetHead,
  },
  {
    params: [],
    name: 'offer-properties.housing-types',
    path: '/housing-types',
    method: ["GET","HEAD"],
    types: {} as HousingTypesGetHead,
  },
  {
    params: [],
    name: 'offer-properties.job-industries',
    path: '/job-industries',
    method: ["GET","HEAD"],
    types: {} as JobIndustriesGetHead,
  },
  {
    params: [],
    name: 'offer-properties.job-types',
    path: '/job-types',
    method: ["GET","HEAD"],
    types: {} as JobTypesGetHead,
  },
  {
    params: [],
    name: 'newsletter.subscribers',
    path: '/newsletter/subscribers',
    method: ["GET","HEAD"],
    types: {} as NewsletterSubscribersGetHead,
  },
  {
    params: [],
    name: 'newsletter.subscribe',
    path: '/newsletter/subscribe',
    method: ["POST"],
    types: {} as NewsletterSubscribePost,
  },
  {
    params: ["id"],
    name: 'newsletter.unsubscribe',
    path: '/newsletter/unsubscribe/:id',
    method: ["GET","HEAD"],
    types: {} as NewsletterUnsubscribeIdGetHead,
  },
  {
    params: [],
    name: 'newsletter.send',
    path: '/newsletter/send',
    method: ["POST"],
    types: {} as NewsletterSendPost,
  },
  {
    params: [],
    name: 'statistics.show',
    path: '/statistics',
    method: ["GET","HEAD"],
    types: {} as StatisticsGetHead,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
