// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type RegisterPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['register'], false>
}
type LoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/auth.ts')['loginValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['login'], true>
}
type LogoutPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/auth_controller.ts').default['logout'], false>
}
type HousingsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['index'], false>
}
type HousingsPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/housing.ts')['postHousingValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['store'], true>
}
type HousingsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['show'], false>
}
type HousingsIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/housing.ts')['putHousingValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['update'], true>
}
type HousingsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_controller.ts').default['destroy'], false>
}
type HousingimagesIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/housing_image_controller.ts').default['show'], false>
}
type HousingimagesIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/housing_image.ts')['housingImageValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/housing_image_controller.ts').default['update'], true>
}
type JobsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['index'], false>
}
type JobsPost = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['store'], false>
}
type JobsIdGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['show'], false>
}
type JobsIdPutPatch = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/job.ts')['putJobValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['update'], true>
}
type JobsIdDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/job_controller.ts').default['destroy'], false>
}
type HousingConditionsGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['housingConditions'], false>
}
type HousingOfferTypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['housingOfferTypes'], false>
}
type HousingTypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['housingTypes'], false>
}
type JobIndustriesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['jobIndustries'], false>
}
type JobTypesGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/offer_properties_controller.ts').default['jobTypes'], false>
}
export interface ApiDefinition {
  'register': {
    '$url': {
    };
    '$post': RegisterPost;
  };
  'login': {
    '$url': {
    };
    '$post': LoginPost;
  };
  'logout': {
    '$url': {
    };
    '$post': LogoutPost;
  };
  'housings': {
    '$url': {
    };
    '$get': HousingsGetHead;
    '$head': HousingsGetHead;
    '$post': HousingsPost;
    ':id': {
      '$url': {
      };
      '$get': HousingsIdGetHead;
      '$head': HousingsIdGetHead;
      '$put': HousingsIdPutPatch;
      '$patch': HousingsIdPutPatch;
      '$delete': HousingsIdDelete;
    };
  };
  'housing-images': {
    ':id': {
      '$url': {
      };
      '$get': HousingimagesIdGetHead;
      '$head': HousingimagesIdGetHead;
      '$put': HousingimagesIdPutPatch;
      '$patch': HousingimagesIdPutPatch;
    };
  };
  'jobs': {
    '$url': {
    };
    '$get': JobsGetHead;
    '$head': JobsGetHead;
    '$post': JobsPost;
    ':id': {
      '$url': {
      };
      '$get': JobsIdGetHead;
      '$head': JobsIdGetHead;
      '$put': JobsIdPutPatch;
      '$patch': JobsIdPutPatch;
      '$delete': JobsIdDelete;
    };
  };
  'housing-conditions': {
    '$url': {
    };
    '$get': HousingConditionsGetHead;
    '$head': HousingConditionsGetHead;
  };
  'housing-offer-types': {
    '$url': {
    };
    '$get': HousingOfferTypesGetHead;
    '$head': HousingOfferTypesGetHead;
  };
  'housing-types': {
    '$url': {
    };
    '$get': HousingTypesGetHead;
    '$head': HousingTypesGetHead;
  };
  'job-industries': {
    '$url': {
    };
    '$get': JobIndustriesGetHead;
    '$head': JobIndustriesGetHead;
  };
  'job-types': {
    '$url': {
    };
    '$get': JobTypesGetHead;
    '$head': JobTypesGetHead;
  };
}
const routes = [
  {
    params: [],
    name: 'auth.register',
    path: '/register',
    method: ["POST"],
    types: {} as RegisterPost,
  },
  {
    params: [],
    name: 'auth.login',
    path: '/login',
    method: ["POST"],
    types: {} as LoginPost,
  },
  {
    params: [],
    name: 'auth.logout',
    path: '/logout',
    method: ["POST"],
    types: {} as LogoutPost,
  },
  {
    params: [],
    name: 'housings.index',
    path: '/housings',
    method: ["GET","HEAD"],
    types: {} as HousingsGetHead,
  },
  {
    params: [],
    name: 'housings.store',
    path: '/housings',
    method: ["POST"],
    types: {} as HousingsPost,
  },
  {
    params: ["id"],
    name: 'housings.show',
    path: '/housings/:id',
    method: ["GET","HEAD"],
    types: {} as HousingsIdGetHead,
  },
  {
    params: ["id"],
    name: 'housings.update',
    path: '/housings/:id',
    method: ["PUT","PATCH"],
    types: {} as HousingsIdPutPatch,
  },
  {
    params: ["id"],
    name: 'housings.destroy',
    path: '/housings/:id',
    method: ["DELETE"],
    types: {} as HousingsIdDelete,
  },
  {
    params: ["id"],
    name: 'housing_images.show',
    path: '/housing-images/:id',
    method: ["GET","HEAD"],
    types: {} as HousingimagesIdGetHead,
  },
  {
    params: ["id"],
    name: 'housing_images.update',
    path: '/housing-images/:id',
    method: ["PUT","PATCH"],
    types: {} as HousingimagesIdPutPatch,
  },
  {
    params: [],
    name: 'jobs.index',
    path: '/jobs',
    method: ["GET","HEAD"],
    types: {} as JobsGetHead,
  },
  {
    params: [],
    name: 'jobs.store',
    path: '/jobs',
    method: ["POST"],
    types: {} as JobsPost,
  },
  {
    params: ["id"],
    name: 'jobs.show',
    path: '/jobs/:id',
    method: ["GET","HEAD"],
    types: {} as JobsIdGetHead,
  },
  {
    params: ["id"],
    name: 'jobs.update',
    path: '/jobs/:id',
    method: ["PUT","PATCH"],
    types: {} as JobsIdPutPatch,
  },
  {
    params: ["id"],
    name: 'jobs.destroy',
    path: '/jobs/:id',
    method: ["DELETE"],
    types: {} as JobsIdDelete,
  },
  {
    params: [],
    name: 'offer-properties.housing-conditions',
    path: '/housing-conditions',
    method: ["GET","HEAD"],
    types: {} as HousingConditionsGetHead,
  },
  {
    params: [],
    name: 'offer-properties.housing-offer-types',
    path: '/housing-offer-types',
    method: ["GET","HEAD"],
    types: {} as HousingOfferTypesGetHead,
  },
  {
    params: [],
    name: 'offer-properties.housing-types',
    path: '/housing-types',
    method: ["GET","HEAD"],
    types: {} as HousingTypesGetHead,
  },
  {
    params: [],
    name: 'offer-properties.job-industries',
    path: '/job-industries',
    method: ["GET","HEAD"],
    types: {} as JobIndustriesGetHead,
  },
  {
    params: [],
    name: 'offer-properties.job-types',
    path: '/job-types',
    method: ["GET","HEAD"],
    types: {} as JobTypesGetHead,
  },
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
