import vine from "@vinejs/vine";

export const postHousingV2Validator = vine.compile(
    vine.object({
        title: vine.string().maxLength(255),
        subtitle: vine.string().maxLength(255).nullable().optional(),
        url: vine.string().nullable().optional(),
        thumbnail: vine.string().nullable().optional(),
        numPhotos: vine.number().positive().nullable().optional(),
        floor: vine.number().nullable().optional(),
        price: vine.number().positive().nullable().optional(),
        currencySuffix: vine.string().maxLength(8).optional(),
        priceDropFormerPrice: vine.number().positive().nullable().optional(),
        priceDropValue: vine.number().positive().nullable().optional(),
        priceDropPercentage: vine.number().positive().nullable().optional(),
        priceByArea: vine.number().positive().nullable().optional(),
        propertyType: vine.string().maxLength(255).nullable().optional(),
        operation: vine.string().maxLength(255).nullable().optional(),
        typology: vine.string().maxLength(255).nullable().optional(),
        subTypology: vine.string().maxLength(255).nullable().optional(),
        size: vine.number().positive().nullable().optional(),
        exterior: vine.boolean().nullable().optional(),
        rooms: vine.number().positive().nullable().optional(),
        bathrooms: vine.number().positive().nullable().optional(),
        address: vine.string().maxLength(255).nullable().optional(),
        province: vine.string().maxLength(255).nullable().optional(),
        municipality: vine.string().maxLength(255).nullable().optional(),
        district: vine.string().maxLength(255).nullable().optional(),
        neighborhood: vine.string().maxLength(255).nullable().optional(),
        region: vine.string().maxLength(255).nullable().optional(),
        subregion: vine.string().maxLength(255).nullable().optional(),
        country: vine.string().maxLength(2).nullable().optional(),
        latitude: vine.number().nullable().optional(),
        longitude: vine.number().nullable().optional(),
        showAddress: vine.boolean().nullable().optional(),
        description: vine.string().nullable().optional(),
        status: vine.string().maxLength(255).optional(),
        hasVideo: vine.boolean().optional(),
        hasPlan: vine.boolean().optional(),
        has3DTour: vine.boolean().optional(),
        has360: vine.boolean().optional(),
        hasStaging: vine.boolean().optional(),
        hasLift: vine.boolean().nullable().optional(),
        hasParkingSpace: vine.boolean().nullable().optional(),
        isParkingSpaceIncludedInPrice: vine.boolean().nullable().optional(),
        parkingSpacePrice: vine.number().positive().nullable().optional()
    })
);

export const putHousingV2Validator = vine.compile(
    vine.object({
        title: vine.string().maxLength(255),
        subtitle: vine.string().maxLength(255).nullable(),
        url: vine.string().nullable(),
        thumbnail: vine.string().nullable(),
        numPhotos: vine.number().positive().nullable(),
        floor: vine.number().nullable(),
        price: vine.number().positive().nullable(),
        currencySuffix: vine.string().maxLength(8),
        priceDropFormerPrice: vine.number().positive().nullable(),
        priceDropValue: vine.number().positive().nullable(),
        priceDropPercentage: vine.number().positive().nullable(),
        priceByArea: vine.number().positive().nullable(),
        propertyType: vine.string().maxLength(255).nullable(),
        operation: vine.string().maxLength(255).nullable(),
        typology: vine.string().maxLength(255).nullable(),
        subTypology: vine.string().maxLength(255).nullable(),
        size: vine.number().positive().nullable(),
        exterior: vine.boolean().nullable(),
        rooms: vine.number().positive().nullable(),
        bathrooms: vine.number().positive().nullable(),
        address: vine.string().maxLength(255).nullable(),
        province: vine.string().maxLength(255).nullable(),
        municipality: vine.string().maxLength(255).nullable(),
        district: vine.string().maxLength(255).nullable(),
        neighborhood: vine.string().maxLength(255).nullable(),
        region: vine.string().maxLength(255).nullable(),
        subregion: vine.string().maxLength(255).nullable(),
        country: vine.string().maxLength(2).nullable(),
        latitude: vine.number().nullable(),
        longitude: vine.number().nullable(),
        showAddress: vine.boolean().nullable(),
        description: vine.string().nullable(),
        status: vine.string().maxLength(255),
        hasVideo: vine.boolean(),
        hasPlan: vine.boolean(),
        has3DTour: vine.boolean(),
        has360: vine.boolean(),
        hasStaging: vine.boolean(),
        hasLift: vine.boolean().nullable(),
        hasParkingSpace: vine.boolean().nullable(),
        isParkingSpaceIncludedInPrice: vine.boolean().nullable(),
        parkingSpacePrice: vine.number().positive().nullable(),
        isAvailable: vine.boolean()
    })
);

export const patchHousingV2Validator = vine.compile(
    vine.object({
        title: vine.string().maxLength(255).nullable().optional(),
        subtitle: vine.string().maxLength(255).nullable().optional(),
        url: vine.string().nullable().optional(),
        thumbnail: vine.string().nullable().optional(),
        numPhotos: vine.number().positive().nullable().optional(),
        floor: vine.number().nullable().optional(),
        price: vine.number().positive().nullable().optional(),
        currencySuffix: vine.string().maxLength(8).optional(),
        priceDropFormerPrice: vine.number().positive().nullable().optional(),
        priceDropValue: vine.number().positive().nullable().optional(),
        priceDropPercentage: vine.number().positive().nullable().optional(),
        priceByArea: vine.number().positive().nullable().optional(),
        propertyType: vine.string().maxLength(255).nullable().optional(),
        operation: vine.string().maxLength(255).nullable().optional(),
        typology: vine.string().maxLength(255).nullable().optional(),
        subTypology: vine.string().maxLength(255).nullable().optional(),
        size: vine.number().positive().nullable().optional(),
        exterior: vine.boolean().nullable().optional(),
        rooms: vine.number().positive().nullable().optional(),
        bathrooms: vine.number().positive().nullable().optional(),
        address: vine.string().maxLength(255).nullable().optional(),
        province: vine.string().maxLength(255).nullable().optional(),
        municipality: vine.string().maxLength(255).nullable().optional(),
        district: vine.string().maxLength(255).nullable().optional(),
        neighborhood: vine.string().maxLength(255).nullable().optional(),
        region: vine.string().maxLength(255).nullable().optional(),
        subregion: vine.string().maxLength(255).nullable().optional(),
        country: vine.string().maxLength(2).nullable().optional(),
        latitude: vine.number().nullable().optional(),
        longitude: vine.number().nullable().optional(),
        showAddress: vine.boolean().nullable().optional(),
        description: vine.string().nullable().optional(),
        status: vine.string().maxLength(255).optional(),
        hasVideo: vine.boolean().optional(),
        hasPlan: vine.boolean().optional(),
        has3DTour: vine.boolean().optional(),
        has360: vine.boolean().optional(),
        hasStaging: vine.boolean().optional(),
        hasLift: vine.boolean().nullable().optional(),
        hasParkingSpace: vine.boolean().nullable().optional(),
        isParkingSpaceIncludedInPrice: vine.boolean().nullable().optional(),
        parkingSpacePrice: vine.number().positive().nullable().optional(),
        isAvailable: vine.boolean().optional()
    })
);
